project:
  type: website
  output-dir: docs

website:
  title: "Curieux.JY"
  favicon: profile.png
  google-analytics: "G-2NVZN2MJZT"
  navbar:
    right:
      - about.qmd
      - projects.qmd
      - note.qmd
      - icon: github
        href: https://github.com/curieuxjy
  comments: # https://h.readthedocs.io/projects/client/en/latest/publishers/config.html
    hypothesis: 
      theme: clean
      openSidebar: false
  page-footer: 
    left: "Copyright 2024, Jung Yeon Lee" 
    right: 
      - icon: github
        href: https://github.com/curieuxjy

format:
  html:
    # title-block-style: default
    fontsize: 12pt
    linestretch: 2.0
    code-line-numbers: true
    page-layout: full
    html-math-method: katex
    theme:
      light: minty
      dark: [minty, theme-dark.scss]
      # [minty, theme-dark.scss]
      # - minty
      # - custom.scss
# https://quarto.org/docs/websites/website-blog.html#themes 
# sketchy simplex standstone minty pulse lux
# https://quarto.org/docs/output-formats/html-themes.html#custom-themes
# https://quarto.org/docs/output-formats/html-themes-more.html

execute:
  freeze: auto 