project:
  type: website
  output-dir: docs

website:
  title: "Curieux.JY"
  favicon: profile.png
  google-analytics: "G-2NVZN2MJZT"
  navbar:
    right:
      - about.qmd
      - note.qmd
      - icon: github
        href: https://github.com/curieuxjy
  comments: 
    hypothesis:
      theme: clean
      openSidebar: false

format:
  html:
    # title-block-style: default
    fontsize: 12pt
    linestretch: 2.0
    code-line-numbers: true
    page-layout: full
    html-math-method: katex
    theme:
      - minty
      - custom.scss
# https://quarto.org/docs/websites/website-blog.html#themes 
# sketchy simplex standstone minty pulse lux
# https://quarto.org/docs/output-formats/html-themes.html#custom-themes
# https://quarto.org/docs/output-formats/html-themes-more.html

execute:
  freeze: auto 