project:
  type: website
  output-dir: docs

website:
  title: "Jung Yeon"
  favicon: profile.png
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/curieuxjy

format:
  html:
    # title-block-style: default
    page-layout: full
    html-math-method: katex
    theme:
      - lux
      # - custom.scss
# https://quarto.org/docs/websites/website-blog.html#themes sketchy simplex standstone
# minty pulse

execute: 
  freeze: auto
